spring:
  application:
    name: employee

  jpa:
    show-sql: true
    properties:
      show-sql: true
    defer-datasource-initialization: true
  datasource:
  url: jdbc:h2:mem:employeedb
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

server:
  port: 8090

